### ISSUE TITLE
error: command 'gcc' failed with exit status 1

### ISSUE THREAD

**Issue by xigrug** [peterkuma/ccplot#2]
I have installed all required：
Python >= 2.6 and < 3.0, including development files
cython
numpy
matplotlib
basemap
libhdf4
libhdfeos2
————————
and I run
sudo yum -y install gcc gcc-c++ kernel-devel
sudo yum -y install python-devel libxslt-devel libffi-devel openssl-devel
try to fix this problem，but it doesn't work

**Comment by peterkuma** [comment]
Hi xigrug,

Sorry for responding to your bug report so late. Can you please post the full output of `setup.py build` and your operating system name/version? I suppose you are using Fedora or openSUSE? I have only tested ccplot on Debian, there might be something different about your OS. I noticed you posted another report regarding running ccplot on Windows - use Linux if you can, it should be easier to set up there.

Many thanks,

Peter

**Comment by peterkuma** [comment]
Closing this issue because of lack of information. The installation instructions have changed substantially in ccplot 2.0.0 and have been tested on Ubuntu 20.04, 21.10, Fedora 35, Debian 11, Devuan 4, Windows 10 and macOS Monterey (Intel).
