### ISSUE TITLE
Iinstall on window but not work

### ISSUE THREAD

**Issue by xigrug** [peterkuma/ccplot#3]
conda list ccplot
# packages in environment at C:\ProgramData\Anaconda2:
#
ccplot                    1.5.2                     <pip>
——————————————————————
ccplot -v
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda2\Scripts\/ccplot", line 56, in <module>
    from ccplot.hdf import HDF
ImportError: DLL load failed: %1 not Win32 。

**Comment by peterkuma** [comment]
The recommended way of installing ccplot on Windows is now under the "Windows Subsystem for Linux". Therefore, this issue should be no longer relevant.
