### ISSUE TITLE
ImportError: cannot import name basemap

### ISSUE THREAD

**Issue by krishnaap** [peterkuma/ccplot#6]
I tried to install ccplot in Ubuntu 19.04, but it shows. 
```
Traceback (most recent call last):
  File "/usr/local/bin/ccplot", line 53, in <module>
    from mpl_toolkits import basemap
ImportError: cannot import name basemap
```
But I already installed Basemap

**Comment by peterkuma** [comment]
Hi  krishnaap,

Thank you for reporting the bug. It looks like Ubuntu 19.04 no longer offers basemap as a Python 2.7 package. It can be installed manually with:

```
sudo apt-get install libgeos-dev python-pyproj
pip install --upgrade --user matplotlib
wget https://github.com/matplotlib/basemap/archive/v1.1.0.tar.gz
tar xf v1.1.0.tar.gz
cd basemap-1.1.0
python setup.py install --user
```

Hopefully it will work on your system, it can sometimes get complicated if multiple versions of packages are installed. A better solution would be if I update ccplot to support Python 3, but right now this solution is faster even if not ideal.

**Comment by peterkuma** [comment]
ccplot 1.5.4 adds support for Python 3, which means `python3-mpltoolkits.basemap` can be installed from the system repositories.
