### ISSUE TITLE
cannot import name 'dedent' from 'matplotlib.cbook'

### ISSUE THREAD

**Issue by bejucoo** [peterkuma/ccplot#8]
Hello,

I had an error using `ccplot v1.5.4`. I just upgraded to `1.5.5` and still have the same error:

```
Traceback (most recent call last):
  File "/usr/local/bin/ccplot", line 54, in <module>
    from mpl_toolkits import basemap
  File "/usr/lib/python3/dist-packages/mpl_toolkits/basemap/__init__.py", line 50, in <module>
    from .proj import Proj
  File "/usr/lib/python3/dist-packages/mpl_toolkits/basemap/proj.py", line 6, in <module>
    from matplotlib.cbook import dedent
ImportError: cannot import name 'dedent' from 'matplotlib.cbook' (/home/pierre/.local/lib/python3.8/site-packages/matplotlib/cbook/__init__.py)
```
I have `matplotlib v3.3.4` and `python 3.8.6` installed on Ubuntu 20.1. Any idea of what's going on?

**Comment by peterkuma** [comment]
I think this error is not related to ccplot, but due to incompatible versions of matplotlib and basemap. Can you try installing the latest basemap version from their GitHub repository? It is now described on the installation page (https://ccplot.org/download/):

> On Ubuntu 20.10, the system basemap library version (1.2.1) is incompatible with the system matplotlib library version. Install basemap from the upstream repository instead:

```sh
apt purge python3-mpltoolkits.basemap
apt install python3-pip git libgeos-dev
pip3 install --user git+https://github.com/matplotlib/basemap.git
```

**Comment by peterkuma** [comment]
I have also added this to Known Issues at https://ccplot.org/download/.

**Comment by bejucoo** [comment]
I installed the upstream repo but now I have this error:

```
Traceback (most recent call last):
  File "/usr/local/bin/ccplot", line 54, in <module>
    from mpl_toolkits import basemap
ImportError: cannot import name 'basemap' from 'mpl_toolkits' (unknown location)
```
I tried using sudo and also with and without the `--user` flag but still doesn't work. I also re-installed ccplot after installing basemap.

**Comment by peterkuma** [comment]
What is your operating system? Can you try uninstalling basemap and installing it again?

```sh
pip3 uninstall basemap # run multiple times until there are no installed versions remaining.
pip3 install --user git+https://github.com/matplotlib/basemap.git
```

**Comment by bejucoo** [comment]
I have Ubuntu 20.1. I ran the commands and it `Successfully installed basemap-1.2.2+dev` but I still got the same error.

**Comment by bejucoo** [comment]
I re-installed python3-mpltoolkits.basemap using `sudo apt install python3-mpltoolkits.basemap` and then re-installed basemap using `pip3 install --user git+https://github.com/matplotlib/basemap.git`. It seems like it's working now:
```
ccplot 1.5.5

Third-party libraries:
matplotlib 3.3.4
basemap 1.2.2+dev

Copyright (c) 2009-2015 Peter Kuma.
This software is provided under the terms of a 2-clause BSD licence.
```

**Comment by peterkuma** [comment]
Great to hear! I think situation like yours can happen because mpl_toolkits is a "namespace package" which can be split across multiple locations, and matplotlib or basemap installed in the system and user's home directory can clash.

I will close this issue now. If you find other problems feel free to re-open.
